### ISSUE TITLE
Can't run it in mac

### ISSUE THREAD

**Issue by fernhw** [crazyquark/nfc-amiibo#2]
I get a 

zsh: permission denied: ./nfc-amiibo

tried chmod +x ./nfc-amiibo

but still can't get it to work. Is there anything I can do to make it work, it's a unix executable on a unix based machine

Mohave 10.14.6 (18G103), Macbook Pro 15' 2019 | have a ACR122U as a reader and several tags 

PS. libnfc does interact with my NFC writter

**Comment by fernhw** [comment]
You can be direct this is outside of my area but I'm still a software engineer.

**Comment by fernhw** [comment]
Solved.

**Comment by rcolsm** [comment]
I exactly have the same problem, how did you solve that?

**Comment by fernhw** [comment]
had to disable the process taking up the nfc reader

**Comment by crazyquark** [comment]
Yes, on macOS there is a daemon holding the NFC reader, I forget what it is called, I think pccsd or something like that.
This is a known libnfc issue(which is what this program uses to access the NFC reader).
