### ISSUE TITLE
Cannot execute binary: Exec format error

### ISSUE THREAD

**Issue by mynameishamish** [crazyquark/nfc-amiibo#3]
Apologies if this is a stupid issue, but when I try to run the nfc-amiibo file on Rpi3 with Raspian I get the error "cannot execute binary: Exec format error". Looking around it seems like this means it isn't compiled for the Pi, but I thought this program was?

**Comment by crazyquark** [comment]
That's weird. It should compile file on the Pi since the original program was meant just for that.
Sounds indeed like you have an architecture mismatch in your binary.

**Comment by crazyquark** [comment]
OK, just compiled this on ARM machine and it runs.
I think you compiled it on an x86 machine and then tried to run it on a raspberry pi(ARM).

It cannot work like that.

You need to compile it on the host you want to run it.
I will close this issue for now but feel free to reopen if I can help further.
