### ISSUE TITLE
Could not open ~/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin

### ISSUE THREAD

**Issue by Payme42** [crazyquark/nfc-amiibo#5]
once more i have an error i cant find awnsers to, 

Could not open ~/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin

im using wls2 and ubuntu

**Comment by Edduaardo** [comment]
Are you using single or double quotes when passing this parameter?
Try this: `"~/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin"`
When you have spaces on the name of the file use double/single quotes.
If this still does not work try using the full path instead of `~` (with quotes).

**Comment by Payme42** [comment]
I was this is the whole command

./nfc-amiibo ~/key_retail.bin "~/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin"

**Comment by Payme42** [comment]
could not open either way
Could not open C:/Users/Payne4108/Documents/Amiiiiiiibo/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin
Could not open ~/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin

**Comment by Payme42** [comment]
there is a tilda ~ tho in the commoand right?


./nfc-amiibo ~/key_retail.bin "C:/Users/Payne4108/Documents/Amiiiiiiibo/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin"

and key_retail.bin is in C:/Users/Payne4108/Documents/Amiiiiiiibo/key_retail.bin 

but 

./nfc-amiibo "~/key_retail.bin" "~/[SSB] 10 - Pikachu.bin"

doesnt work i even moved them both to the same location

**Comment by Payme42** [comment]
missclick

**Comment by Edduaardo** [comment]
You said you are using WLS2 Ubuntu right? The path that WLS uses is not C:, it's /mnt/c/.
But I think the correct path should be `"~/Documents/Amiiiiiiibo/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin"`
Try this command: `./nfc-amiibo ~/Documents/Amiiiiiiibo/key_retail.bin "~/Documents/Amiiiiiiibo/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin"`
If still gives you error, try the full path, it should be `"/mnt/c/Users/Payne4108/Documents/Amiiiiiiibo/Animal Crossing/Cards/Series 2/[AC] 188 - Ankha.bin"`

It's seems that you don't understand what ~ means in Linux, it's appointment to your home folder i.e. your `C:/Users/Payne4108` or `/mnt/c/Users/Payne4108`.

**Comment by Payme42** [comment]
no such file or directory

**Comment by Edduaardo** [comment]
Are you _sure_ the file actually exists in the path that you are passing as parameter?

**Comment by Payme42** [comment]
yes i have it right here
![image](https://user-images.githubusercontent.com/45109917/103900508-deb33d00-50c5-11eb-945f-d2e9284f4375.png)

**Comment by Payme42** [comment]
i am using cd nfc-amiibo 
idk if that changes somthing

**Comment by Payme42** [comment]
![image](https://user-images.githubusercontent.com/45109917/103900949-77e25380-50c6-11eb-8a39-ccda8b0ead1f.png)

**Comment by Edduaardo** [comment]
Again, it's wrong. Try the last command. You forgot the dot in `./nfc-amiibo` and the key file is not in `~/key_retailt.bin` it's in `/mnt/c/Users/Payne4108/Documents/Amiiiiiiibo/key_retail.bin`. 
I won't reply anymore since it's not a problem with the program.
I really recommend you about learning Command Line and how directory works if you really want to continue doing this.

**Comment by Payme42** [comment]
It worked! but not for the amiibo file ill try using a differnt one thank you

**Comment by Payme42** [comment]
oh lol just an update if anyone else has this problem, make sure the nfc reader is pluygged in
