### ISSUE TITLE
Make creates bad binary file

### ISSUE THREAD

**Issue by jlc42** [crazyquark/nfc-amiibo#8]
On raspberry Pi, make seems to run and creates an executable, but when it is run, I get the following error:

bash: ./nfc-amiibo: cannot execute binary file: Exec format error

**Comment by jlc42** [comment]
However, weirdly enough, make clean, followed by make, seems to have created a working executable.

**Comment by crazyquark** [comment]
That's my fault, I had committed the binary in the repo so make was not building it and you were trying to run the x86 binary.
I fixed it yesterday.
